#!/bin/bash
echo clear
echo Unload Apps from memory utility for libreperf kernel extension 01Alpha
if [ ! -f "/libreperfruntime/sys/kernelmsg" ]; then
  echo libreperfkernelmanagement communication failed please do a full restart
  exit
else
  cat /libreperfruntime/runtimedebugmsg ; cat /libreperfruntime/sys/kernelmsg
  sleep 2
  echo [1] Communication established
fi

echo 1 > /libreperfruntime/sys/dumptodisk

echo [2] userspace operation executed
sleep 1
sleep 1
exit
