#!/bin/bash
echo clear
echo Unload Apps from memory utility for libreperf kernel extension 01Alpha
if [ ! -f "/Volumes/libreperfruntime/sys/kernelmsg" ]; then
  echo libreperfkernelmanagement communication failed please do a full restart
  exit
else
  cat /Volumes/libreperfruntime/sys/kernelmsg
  sleep 2
  echo [1] Communication established
fi
echo saving contents
cd /Users/; for i in *; do sudo cp -r /Volumes/systemcacheblock0/"$i"/ /Users/"$i"/Library/Caches_hdd; done
cd /Users/; for i in *; do sudo cp -r /Volumes/prefetchblock0/"$i"/ /Users/"$i"/Library/Application\ Support\ HDD; done
echo purging memory from ram
cd /Users/; for i in *; do rm -rf /Volumes/prefetchblock0/"$i"/; done
cd /Users/; for i in *; do rm -rf /Volumes/systemcacheblock0/"$i"/; done

echo [2] userspace operation executed
sleep 1
sleep 1
exit
